# Funding options for NOESIS - Digital Daimon
# These are displayed in the "Sponsor" button on the repository

# GitHub Sponsors username
github: JuanCS-Dev

# Custom funding URLs
# custom: ['https://noesis.dev/sponsor']
