"""Security Patterns for Zero Trust Enforcement.

Pattern definitions for security checks.
"""

from __future__ import annotations


# Authentication patterns
AUTH_PATTERNS: list[str] = [
    r"@authenticate",
    r"@authorize",
    r"check_permission",
    r"verify_auth",
    r"require_auth",
    r"is_authenticated",
]

# Input validation patterns
VALIDATION_PATTERNS: list[str] = [
    r"validate_input",
    r"sanitize",
    r"escape",
    r"verify",
    r"check_",
    r"assert",
]

# Audit trail patterns
AUDIT_PATTERNS: list[str] = [
    r"audit_log",
    r"log_action",
    r"record_event",
    r"track_",
]

# Dangerous trust assumption patterns
DANGEROUS_PATTERNS: list[str] = [
    r"# assume .* is trusted",
    r"# trust .*",
    r"skip.*validation",
    r"bypass.*auth",
    r"disable.*security",
    r"TRUSTED_",
    r"allow_all",
    r"permit_all",
    r"no_auth",
]

# AI-generated code markers
AI_MARKERS: list[str] = [
    "Generated by Claude",
    "AI-generated",
    "Copilot",
    "Generated with",
    "Auto-generated by",
]

# Endpoint detection patterns
ENDPOINT_PATTERNS: list[str] = [
    r"@app\.(get|post|put|delete|patch)",
    r"@router\.(get|post|put|delete|patch)",
    r"def (get|post|put|delete|handle)_",
    r"class.*Handler",
    r"class.*View",
]

# User input patterns
INPUT_PATTERNS: list[str] = [
    r"request\.(json|data|form|args|params)",
    r"input\(",
    r"raw_input\(",
    r"sys\.argv",
    r"os\.environ",
    r"request\.get",
]

# Critical operations requiring audit
CRITICAL_OPERATIONS: list[str] = [
    r"delete",
    r"remove",
    r"update.*permission",
    r"grant.*access",
    r"revoke",
    r"modify.*config",
    r"change.*password",
    r"reset",
    r"override",
]
